all_solvers = [ "MNE", "wMNE", "dSPM", 
                "LORETA", "sLORETA", "eLORETA", 
                "LAURA", "Backus-Gilbert", 
                "S-MAP",
                "Champagne", "Multiple Sparse Priors", "Bayesian LORETA", "Bayesian MNE", "Bayesian Beamformer", "Bayesian Beamformer LORETA",
                "Fully-Connected", 
                "LUCAS",
                "FISTA",
                "OMP", "COSAMP", "SOMP", "REMBO", "SP",
                "SMP", "SSMP", 
            ]